name: havillah
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.4
  reactive_forms: ^16.1.1
  dio: ^5.4.0
  get_it: ^7.6.7
  http: ^1.2.0
  font_awesome_flutter: ^10.7.0
  fancy_password_field: ^2.0.3
  motion_toast: ^2.8.0
  easy_loading_button: ^0.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/